fields:
  - name: "city"
    type: "STRING"
  - name: "lon"
    type: "FLOAT64"
  - name: "lat"
    type: "FLOAT64"
  - name: "aqi"
    type: "FLOAT64"
  - name: "co"
    type: "FLOAT64"
  - name: "no"
    type: "FLOAT64"
  - name: "no2"
    type: "FLOAT64"
  - name: "o3"
    type: "FLOAT64"
  - name: "so2"
    type: "FLOAT64"
  - name: "pm2_5" 
    type: "FLOAT64"
  - name: "pm10"
    type: "FLOAT64"
  - name: "nh3"
    type: "FLOAT64"
  - name: "timestamp"
    type: "TIMESTAMP"
            
            
            